spring.application.name=category-api
spring.threads.virtual.enabled=true
spring.data.mongodb.auto-index-creation=true

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/neAvito}
server.port=${SERVER_PORT:8080}