spring.application.name=banner-api
spring.threads.virtual.enabled=true

spring.cloud.aws.s3.endpoint=http://localhost:9000
spring.cloud.aws.s3.path-style-access-enabled=true
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=password
spring.cloud.aws.region.static=us-east-1

storage.s3.bucket=banner

server.port=8000

spring.data.mongodb.uri=mongodb://localhost:27017/neAvito