spring.application.name=banner-api
spring.threads.virtual.enabled=true
spring.data.mongodb.auto-index-creation=true

spring.cloud.aws.s3.endpoint=${S3_ENDPOINT:http://localhost:9000}
spring.cloud.aws.s3.path-style-access-enabled=true
spring.cloud.aws.credentials.access-key=${S3_ACCESS_KEY:test}
spring.cloud.aws.credentials.secret-key=${S3_SECRET_KEY:password}
spring.cloud.aws.region.static=us-east-1

storage.s3.bucket=${S3_BUCKET:banner}

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/neAvito}

clients.category-api=${CATEGORY_API_URL:http://category-api}
server.port=${SERVER_PORT:8080}