name: Test Check

on:
  pull_request:

jobs:
  test:
    name: My Test Check
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "GitHub Actions работает!"
          echo "Это тестовая проверка."
